### ISSUE TITLE
Version 0.5.0 not published correctly to npm?

### ISSUE THREAD

**Issue by AndrWeisR** [emilbayes/cordova-plugin-android-downloadmanager#8]
Hi Emil,

I see you merged in my DownloadManager.addCompletedDownload change [here](https://github.com/emilbayes/cordova-plugin-android-downloadmanager/pull/5), but it looks like this isn't published to the npm package properly. When I do `npm install cordova-plugin-android-downloadmanager` I get 0.5.0, but the node module doesn't contain the addCompletedDownload change.

**Comment by AndrWeisR** [comment]
Hi Emil, can you fix this please?

**Comment by emilbayes** [comment]
@AndrWeisR Sorry, should be coming out now as 1.0.0
